### ISSUE TITLE
Setting up unit tests

### ISSUE THREAD

**Issue by SirMishaa** [qcarpentier/lovelace#12]
Having unit tests is essential to have a solid application and to track bugs. 

**We have to choose between three testing frameworks :** 
- Jasmine
- Mocha 
- Jest

These are the most popular and most used. In line with [**Grafikart's series**](https://www.grafikart.fr/tutoriels/presentation-1088) on the subject, I'm thinking **about choosing Mocha** for the following reason : 

_Mocha is a rather peculiar framework, because it comes with no library to manage assertions and no way to create Mocks. The advantage is that we will be able to use the modules we want to use to manage these tasks and adapt the Framework to our desires._ 

**I will first follow the Grafikart series in order to be comfortable with the unit tests in Javascript and to choose the most suitable and adequate test framework.**

Don't hesitate also to give me your opinions.

**Comment by qcarpentier** [comment]
Mocha seems to be ok and easy to handle. Also see this article: 
https://www.codementor.io/@codementorteam/javascript-testing-framework-comparison-jasmine-vs-mocha-8s9k27za3
